export const ASTEROIDS_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
export function createAsteroidsGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createAsteroidsGame: canvas obrigatório.');const c=canvas.getContext('2d');canvas.width=320;canvas.height=280;
 let state='ready',raf=0,score=0,destroyed=false,spawn=0;const ship={x:160,y:140,a:-Math.PI/2,vx:0,vy:0},rocks=[],shots=[];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)},wrap=(v,m)=>(v+m)%m;
 function reset(){ship.x=160;ship.y=140;ship.a=-Math.PI/2;ship.vx=ship.vy=0;rocks.length=shots.length=0;spawn=0;pts(0);draw()}
 function fire(){if(state==='playing'&&shots.length<7)shots.push({x:ship.x,y:ship.y,vx:Math.cos(ship.a)*6,vy:Math.sin(ship.a)*6,life:60})}
 function input(d){if(d==='left')ship.a-=.22;else if(d==='right')ship.a+=.22;else if(d==='up'){ship.vx+=Math.cos(ship.a)*.55;ship.vy+=Math.sin(ship.a)*.55}}
 function draw(){c.clearRect(0,0,320,280);c.strokeStyle='#173216';c.lineWidth=2;c.save();c.translate(ship.x,ship.y);c.rotate(ship.a);c.beginPath();c.moveTo(12,0);c.lineTo(-9,-7);c.lineTo(-5,0);c.lineTo(-9,7);c.closePath();c.stroke();c.restore();rocks.forEach(r=>{c.beginPath();c.arc(r.x,r.y,r.r,0,Math.PI*2);c.stroke()});c.fillStyle='#173216';shots.forEach(s=>c.fillRect(s.x,s.y,3,3))}
 function loop(){if(state!=='playing'||destroyed)return;spawn--;if(spawn<=0){const edge=Math.floor(Math.random()*4),r=10+Math.random()*14,x=edge===0?0:edge===1?320:Math.random()*320,y=edge===2?0:edge===3?280:Math.random()*280,a=Math.atan2(ship.y-y,ship.x-x)+(Math.random()-.5)*.8;rocks.push({x,y,r,vx:Math.cos(a)*(1+Math.random()),vy:Math.sin(a)*(1+Math.random())});spawn=55+Math.random()*55}ship.x=wrap(ship.x+ship.vx,320);ship.y=wrap(ship.y+ship.vy,280);ship.vx*=.99;ship.vy*=.99;rocks.forEach(r=>{r.x=wrap(r.x+r.vx,320);r.y=wrap(r.y+r.vy,280)});shots.forEach(s=>{s.x=wrap(s.x+s.vx,320);s.y=wrap(s.y+s.vy,280);s.life--});
 for(const s of shots)for(const r of rocks)if(r.r>0&&Math.hypot(s.x-r.x,s.y-r.y)<r.r){r.r=0;s.life=0;pts(score+10)}for(let i=rocks.length-1;i>=0;i--)if(rocks[i].r<=0)rocks.splice(i,1);for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1);if(rocks.some(r=>Math.hypot(ship.x-r.x,ship.y-r.y)<r.r+7)){emit('game_over');draw();return}draw();raf=requestAnimationFrame(loop)}
 const start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing');raf=requestAnimationFrame(loop)},pause=()=>{if(state==='playing'){cancelAnimationFrame(raf);emit('paused')}},resume=()=>{if(state==='paused'){emit('playing');raf=requestAnimationFrame(loop)}},restart=()=>{cancelAnimationFrame(raf);reset();emit('ready')},action=a=>{if(a==='primary'||a==='tap')fire()},destroy=()=>{destroyed=true;cancelAnimationFrame(raf);c.clearRect(0,0,320,280)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection:input,action,destroy,getScore:()=>score,getState:()=>state};
}