export const FLAPPY_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
export function createFlappyGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createFlappyGame: canvas obrigatório.');const c=canvas.getContext('2d');canvas.width=320;canvas.height=280;
 let state='ready',raf=0,last=0,score=0,destroyed=false,spawn=0;const bird={x:70,y:130,r:9,vy:0},pipes=[];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)};
 function reset(){bird.y=130;bird.vy=0;pipes.length=0;spawn=250;pts(0);draw()}function flap(){bird.vy=-5.8}
 function draw(){c.clearRect(0,0,320,280);c.fillStyle='#173216';c.beginPath();c.arc(bird.x,bird.y,bird.r,0,Math.PI*2);c.fill();pipes.forEach(p=>{c.fillRect(p.x,0,25,p.top);c.fillRect(p.x,p.top+p.gap,25,280-p.top-p.gap)})}
 function loop(t){if(state!=='playing'||destroyed)return;const dt=Math.min(32,t-(last||t));last=t;bird.vy+=.023*dt;bird.y+=bird.vy*dt/16;spawn-=dt;if(spawn<=0){const gap=75,top=35+Math.random()*130;pipes.push({x:330,top,gap,passed:false});spawn=1250}for(const p of pipes){p.x-=2.8*dt/16;if(!p.passed&&p.x+25<bird.x){p.passed=true;pts(score+10)}}while(pipes[0]&&pipes[0].x<-30)pipes.shift();const hit=bird.y-bird.r<0||bird.y+bird.r>280||pipes.some(p=>bird.x+bird.r>p.x&&bird.x-bird.r<p.x+25&&(bird.y-bird.r<p.top||bird.y+bird.r>p.top+p.gap));if(hit){emit('game_over');draw();return}draw();raf=requestAnimationFrame(loop)}
 const start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing');last=0;flap();raf=requestAnimationFrame(loop)},pause=()=>{if(state==='playing'){cancelAnimationFrame(raf);emit('paused')}},resume=()=>{if(state==='paused'){emit('playing');last=0;raf=requestAnimationFrame(loop)}},restart=()=>{cancelAnimationFrame(raf);reset();emit('ready')},setDirection=d=>{if(d==='up')flap()},action=a=>{if(a==='primary'||a==='tap')flap()},destroy=()=>{destroyed=true;cancelAnimationFrame(raf);c.clearRect(0,0,320,280)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection,action,destroy,getScore:()=>score,getState:()=>state};
}