export const FLAPPY_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
export function createFlappyGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createFlappyGame: canvas obrigatório.');const c=canvas.getContext('2d');canvas.width=320;canvas.height=280;
 let state='ready',raf=0,last=0,score=0,destroyed=false,spawn=0;const bird={x:72,y:132,r:8,vy:0},pipes=[];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)};
 function reset(){bird.y=132;bird.vy=0;pipes.length=0;spawn=850;pts(0);draw()}function flap(){if(state==='playing')bird.vy=-4.35}
 function draw(){c.clearRect(0,0,320,280);c.fillStyle='#173216';c.beginPath();c.arc(bird.x,bird.y,bird.r,0,Math.PI*2);c.fill();pipes.forEach(p=>{c.fillRect(p.x,0,25,p.top);c.fillRect(p.x,p.top+p.gap,25,280-p.top-p.gap)})}
 function loop(t){if(state!=='playing'||destroyed)return;const dt=Math.min(28,t-(last||t));last=t;bird.vy+=.016*dt;bird.vy=Math.min(bird.vy,6.2);bird.y+=bird.vy*dt/16;spawn-=dt;if(spawn<=0){const gap=Math.max(90,104-Math.floor(score/40)*3),margin=38,top=margin+Math.random()*(280-gap-margin*2);pipes.push({x:330,top,gap,passed:false});spawn=Math.max(1350,1650-Math.floor(score/50)*45)}const speed=Math.min(2.8,2.15+score/220);for(const p of pipes){p.x-=speed*dt/16;if(!p.passed&&p.x+25<bird.x){p.passed=true;pts(score+10)}}while(pipes[0]&&pipes[0].x<-30)pipes.shift();const hit=bird.y-bird.r<0||bird.y+bird.r>280||pipes.some(p=>bird.x+bird.r-2>p.x&&bird.x-bird.r+2<p.x+25&&(bird.y-bird.r+2<p.top||bird.y+bird.r-2>p.top+p.gap));if(hit){emit('game_over');draw();return}draw();raf=requestAnimationFrame(loop)}
 const start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing');last=0;raf=requestAnimationFrame(loop)},pause=()=>{if(state==='playing'){cancelAnimationFrame(raf);emit('paused')}},resume=()=>{if(state==='paused'){emit('playing');last=0;raf=requestAnimationFrame(loop)}},restart=()=>{cancelAnimationFrame(raf);reset();emit('ready')},setDirection=d=>{if(d==='up')flap()},action=a=>{if(a==='primary'||a==='tap')flap()},destroy=()=>{destroyed=true;cancelAnimationFrame(raf);c.clearRect(0,0,320,280)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection,action,destroy,getScore:()=>score,getState:()=>state};
}