export const IGNITE_MAZE_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
const MAP=["################","#..............#","#.####.##.####.#","#......##......#","###.##....##.###","#...##.##.##...#","#.#..........#.#","#.##.######.##.#","#....#....#....#","####.#.##.#.####","#..............#","################"];
export function createIgniteMazeGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createIgniteMazeGame: canvas obrigatório.');const c=canvas.getContext('2d'),cell=19;canvas.width=MAP[0].length*cell;canvas.height=MAP.length*cell;
 let state='ready',timer=0,score=0,destroyed=false,dir='right',shield=0,items=new Set(),px=1,py=1,tick=0,grace=0;const rivals=[{x:14,y:10,last:null},{x:14,y:1,last:null},{x:8,y:6,last:null}];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)},key=(x,y)=>`${x}:${y}`,open=(x,y)=>MAP[y]?.[x]&&MAP[y][x]!=='#';
 function reset(){items=new Set();for(let y=0;y<MAP.length;y++)for(let x=0;x<MAP[y].length;x++)if(MAP[y][x]==='.')items.add(key(x,y));px=1;py=1;dir='right';shield=0;tick=0;grace=18;[[14,10],[14,1],[8,6]].forEach((p,i)=>{rivals[i].x=p[0];rivals[i].y=p[1];rivals[i].last=null});pts(0);draw()}
 function draw(){c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#173216';for(let y=0;y<MAP.length;y++)for(let x=0;x<MAP[y].length;x++)if(MAP[y][x]==='#')c.fillRect(x*cell,y*cell,cell,cell);items.forEach(k=>{const [x,y]=k.split(':').map(Number);c.fillRect(x*cell+8,y*cell+8,4,4)});c.font='15px sans-serif';c.fillText(shield?'🛡️':'🔥',px*cell+1,py*cell+15);c.fillStyle='#173216';rivals.forEach(g=>c.fillRect(g.x*cell+4,g.y*cell+4,11,11))}
 function rivalStep(g){let options=[[1,0],[-1,0],[0,1],[0,-1]].filter(([a,b])=>open(g.x+a,g.y+b));const reverse=g.last&&[-g.last[0],-g.last[1]];if(options.length>1&&reverse)options=options.filter(([a,b])=>a!==reverse[0]||b!==reverse[1]);if(!options.length)return;options.sort((a,b)=>Math.abs(g.x+a[0]-px)+Math.abs(g.y+a[1]-py)-(Math.abs(g.x+b[0]-px)+Math.abs(g.y+b[1]-py)));const chase=shield?options[options.length-1]:options[0];const ch=Math.random()<(shield?.7:.5)?chase:options[Math.floor(Math.random()*options.length)];g.x+=ch[0];g.y+=ch[1];g.last=ch}
 function step(){tick++;if(grace>0)grace--;if(shield>0)shield--;const D={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},[dx,dy]=D[dir]||[0,0];if(open(px+dx,py+dy)){px+=dx;py+=dy}const k=key(px,py);if(items.delete(k))pts(score+(shield?10:5));if(tick%2===0&&grace<12)rivals.forEach(rivalStep);const hit=rivals.find(g=>g.x===px&&g.y===py);if(hit&&grace===0){if(shield){pts(score+25);hit.x=14;hit.y=10;hit.last=null;shield=Math.max(0,shield-6)}else{clearInterval(timer);emit('game_over')}}else if(!items.size){clearInterval(timer);pts(score+300);emit('game_over')}draw()}
 const setDirection=d=>{if(['up','down','left','right'].includes(d))dir=d},action=a=>{if((a==='primary'||a==='tap')&&state==='playing'&&shield===0&&score>=10){shield=24;pts(score-10);draw()}},start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing');timer=setInterval(step,145)},pause=()=>{if(state==='playing'){clearInterval(timer);emit('paused')}},resume=()=>{if(state==='paused'){emit('playing');timer=setInterval(step,145)}},restart=()=>{clearInterval(timer);reset();emit('ready')},destroy=()=>{destroyed=true;clearInterval(timer);c.clearRect(0,0,canvas.width,canvas.height)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection,action,destroy,getScore:()=>score,getState:()=>state};
}