export const MEMORY_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
export function createMemoryGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createMemoryGame: canvas obrigatório.');const c=canvas.getContext('2d');canvas.width=320;canvas.height=280;const cols=4,rows=4,w=64,h=52,g=8,sx=20,sy=20;
 let state='ready',score=0,destroyed=false,cursor=0,cards=[],open=[];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)};
 function reset(){const vals=[0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7].sort(()=>Math.random()-.5);cards=vals.map(v=>({v,done:false}));open=[];cursor=0;pts(0);draw()}
 function draw(){c.clearRect(0,0,320,280);c.font='24px sans-serif';for(let i=0;i<cards.length;i++){const x=sx+(i%cols)*(w+g),y=sy+Math.floor(i/cols)*(h+g),show=cards[i].done||open.includes(i);c.strokeStyle='#173216';c.lineWidth=i===cursor?4:2;c.strokeRect(x,y,w,h);if(show)c.fillText(['🍔','🍟','🥤','🌮','🍕','🍗','🍰','🔥'][cards[i].v],x+17,y+34)}}
 function reveal(){if(state!=='playing'||cards[cursor].done||open.includes(cursor)||open.length===2)return;open.push(cursor);draw();if(open.length===2){const[a,b]=open;if(cards[a].v===cards[b].v){cards[a].done=cards[b].done=true;open=[];pts(score+20);if(cards.every(x=>x.done)){pts(score+100);emit('game_over')}draw()}else setTimeout(()=>{if(destroyed)return;open=[];pts(Math.max(0,score-2));draw()},500)}}
 function move(d){let r=Math.floor(cursor/cols),col=cursor%cols;if(d==='left')col=Math.max(0,col-1);if(d==='right')col=Math.min(cols-1,col+1);if(d==='up')r=Math.max(0,r-1);if(d==='down')r=Math.min(rows-1,r+1);cursor=r*cols+col;draw()}
 const start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing')},pause=()=>{if(state==='playing')emit('paused')},resume=()=>{if(state==='paused')emit('playing')},restart=()=>{reset();emit('ready')},action=a=>{if(a==='primary'||a==='tap')reveal()},pointer=(x,y)=>{const col=Math.floor((x-sx)/(w+g)),r=Math.floor((y-sy)/(h+g));if(col>=0&&col<cols&&r>=0&&r<rows){cursor=r*cols+col;reveal()}},destroy=()=>{destroyed=true;c.clearRect(0,0,320,280)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection:move,action,pointer,destroy,getScore:()=>score,getState:()=>state};
}