export const MINES_STATE=Object.freeze({READY:'ready',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over'});
export function createMinesweeperGame({canvas,onScoreChange,onStateChange}={}){
 if(!canvas)throw new Error('createMinesweeperGame: canvas obrigatório.');const c=canvas.getContext('2d');canvas.width=320;canvas.height=280;const cols=8,rows=7,cell=34,sx=24,sy=18;
 let state='ready',score=0,destroyed=false,cursor=0,cells=[];
 const emit=s=>{state=s;onStateChange?.(s)},pts=n=>{score=n;onScoreChange?.(n)},idx=(x,y)=>y*cols+x;
 function reset(){cells=Array.from({length:cols*rows},()=>({mine:false,open:false,n:0}));[...cells.keys()].sort(()=>Math.random()-.5).slice(0,8).forEach(i=>cells[i].mine=true);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=idx(x,y);for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const nx=x+xx,ny=y+yy;if(nx>=0&&nx<cols&&ny>=0&&ny<rows&&cells[idx(nx,ny)].mine)cells[i].n++}}cursor=0;pts(0);draw()}
 function draw(){c.clearRect(0,0,320,280);c.font='bold 15px sans-serif';c.textAlign='center';for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=idx(x,y),px=sx+x*cell,py=sy+y*cell;c.strokeStyle='#173216';c.lineWidth=i===cursor?4:1;c.strokeRect(px,py,cell-3,cell-3);if(cells[i].open){if(cells[i].mine)c.fillText('💣',px+15,py+22);else if(cells[i].n)c.fillText(cells[i].n,px+15,py+22)}}c.textAlign='left'}
 function revealAt(i){if(state!=='playing'||cells[i].open)return;cells[i].open=true;if(cells[i].mine){emit('game_over');draw();return}pts(score+5);if(cells[i].n===0){const x=i%cols,y=Math.floor(i/cols);for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const nx=x+xx,ny=y+yy;if(nx>=0&&nx<cols&&ny>=0&&ny<rows){const ni=idx(nx,ny);if(!cells[ni].open&&!cells[ni].mine)cells[ni].open=true}}}if(cells.filter(v=>v.open&&!v.mine).length===cols*rows-8){pts(score+100);emit('game_over')}draw()}
 function move(d){let x=cursor%cols,y=Math.floor(cursor/cols);if(d==='left')x=Math.max(0,x-1);if(d==='right')x=Math.min(cols-1,x+1);if(d==='up')y=Math.max(0,y-1);if(d==='down')y=Math.min(rows-1,y+1);cursor=idx(x,y);draw()}
 const start=()=>{if(state==='game_over')reset();if(state==='playing'||destroyed)return;emit('playing')},pause=()=>{if(state==='playing')emit('paused')},resume=()=>{if(state==='paused')emit('playing')},restart=()=>{reset();emit('ready')},action=a=>{if(a==='primary'||a==='tap')revealAt(cursor)},pointer=(x,y)=>{const gx=Math.floor((x-sx)/cell),gy=Math.floor((y-sy)/cell);if(gx>=0&&gx<cols&&gy>=0&&gy<rows){cursor=idx(gx,gy);revealAt(cursor)}},destroy=()=>{destroyed=true;c.clearRect(0,0,320,280)};
 reset();onStateChange?.(state);return{start,pause,resume,restart,setDirection:move,action,pointer,destroy,getScore:()=>score,getState:()=>state};
}