// Ignite Play 4.0 — biblioteca de jogos sob demanda, mobile-first e isolada de pedidos.
import { getGame, listGames, loadGame } from './game-registry.js';
import { getHighScore, setHighScoreIfBetter } from './score-store.js';

const STYLE_ID='ignite-play-styles',LIBRARY_STYLE_ID='ignite-play-library-styles',LOCK_CLASS='ignite-play-lock',SWIPE_THRESHOLD=22;
const KEY_DIRECTIONS={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right',W:'up',S:'down',A:'left',D:'right'};
const MARKUP=`<div class="ignite-play-overlay" role="dialog" aria-modal="true" aria-labelledby="ignite-play-title"><main class="ignite-play-console"><header class="ignite-play-header"><button type="button" class="ignite-play-iconbtn" data-action="back" aria-label="Voltar">‹</button><div class="ignite-play-heading"><span id="ignite-play-title">IGNITE PLAY</span><small data-role="order-label"></small></div><button type="button" class="ignite-play-iconbtn" data-action="close" aria-label="Fechar">×</button></header><section class="ignite-play-library-view" data-role="library-view"><div class="ignite-play-hero"><span>ARCADE</span><h2>Jogue enquanto espera</h2><p>Seu pedido continua sendo acompanhado em segundo plano.</p></div><div data-role="featured-slot"></div><div class="ignite-play-library-title"><strong>TODOS OS JOGOS</strong><small data-role="game-count"></small></div><div class="ignite-play-library__grid" data-role="game-grid"></div></section><section class="ignite-play-game-view" data-role="game-view" hidden><div class="ignite-play-gamebar"><div><span data-role="game-icon"></span><strong data-role="game-name"></strong></div><span class="ignite-play-live"><i></i><b data-role="state-label">PRONTO</b></span></div><div class="ignite-play-screen"><div class="ignite-play-screen__hud"><div><span>SCORE</span><strong data-role="score">000</strong></div><div><span>RECORDE</span><strong data-role="best">000</strong></div></div><div class="ignite-play-screen__canvas-wrap" data-role="canvas-wrap"><canvas class="ignite-play-canvas" data-role="canvas"></canvas><div class="ignite-play-panel" data-role="panel"></div></div></div><p class="ignite-play-control-hint" data-role="control-hint"></p><div class="ignite-play-controls"><div class="ignite-play-dpad" data-role="dpad" aria-label="Direcionais"><button type="button" data-dir="up" aria-label="Cima">▲</button><button type="button" data-dir="left" aria-label="Esquerda">◀</button><span></span><button type="button" data-dir="right" aria-label="Direita">▶</button><button type="button" data-dir="down" aria-label="Baixo">▼</button></div><div class="ignite-play-actions"><button type="button" data-action="pause">Ⅱ<small>PAUSA</small></button><button type="button" class="is-primary" data-action="a">A<small>JOGAR</small></button></div></div></section></main></div>`;

let overlay=null,activeGame=null,activeMeta=null,currentScore=0,bestScore=0,currentOrderNumber='',onCloseCallback=null,previousFocus=null,keydownHandler=null,pointerStart=null,launchSeq=0;
const q=r=>overlay?.querySelector(`[data-role="${r}"]`);
const formatScore=v=>String(Math.max(0,Math.floor(v))).padStart(3,'0');
const stateLabel=s=>s==='playing'?'JOGANDO':s==='paused'?'PAUSADO':s==='game_over'?'FIM':s==='loading'?'CARREGANDO':'PRONTO';
const ensureStyles=()=>{const styles=[[STYLE_ID,'../../../styles/ignite-play.css'],[LIBRARY_STYLE_ID,'../../../styles/ignite-play-library.css']];styles.forEach(([id,path])=>{if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=new URL(path,import.meta.url).href;document.head.appendChild(l);});};
const gameCard=g=>`<button type="button" class="ignite-play-game-card" data-game-id="${g.id}"><span class="ignite-play-game-card__art">${g.icon}</span><span class="ignite-play-game-card__body"><strong>${g.name}</strong><small>${g.description}</small><em>${g.category} · ${g.controls}</em></span><span class="ignite-play-game-card__meta"><small>HI</small><b>${formatScore(getHighScore(g.id))}</b><i>›</i></span></button>`;
const featuredCard=g=>`<button type="button" class="ignite-play-featured" data-game-id="${g.id}"><span class="ignite-play-featured__badge">⭐ DESTAQUE IGNITE</span><span class="ignite-play-featured__art">${g.icon}</span><span class="ignite-play-featured__body"><strong>${g.name}</strong><small>${g.description}</small><em>HI ${formatScore(getHighScore(g.id))}</em></span><span class="ignite-play-featured__cta">JOGAR ›</span></button>`;

function renderLibrary(){launchSeq++;activeGame?.destroy();activeGame=null;activeMeta=null;currentScore=bestScore=0;q('library-view').hidden=false;q('game-view').hidden=true;overlay.dataset.view='library';delete overlay.dataset.controls;delete overlay.dataset.state;overlay.querySelector('[data-action="back"]').hidden=true;const games=listGames(),featured=games.find(g=>g.featured),regular=games.filter(g=>!g.featured);q('featured-slot').innerHTML=featured?featuredCard(featured):'';q('game-count').textContent=`${games.length} jogos`;q('game-grid').innerHTML=regular.map(gameCard).join('');requestAnimationFrame(()=>overlay?.querySelector('[data-game-id]')?.focus());}
function panelMarkup(s){if(s==='loading')return `<span class="ignite-play-loader" aria-hidden="true"></span><strong>CARREGANDO</strong><p>Preparando ${activeMeta?.name||'o jogo'}…</p>`;if(s==='ready')return `<span class="ignite-play-panel__icon">${activeMeta.icon}</span><strong>${activeMeta.name}</strong><p>${activeMeta.description}</p><button data-action="a">JOGAR AGORA</button>`;if(s==='paused')return `<strong>PAUSADO</strong><p>Seu pedido continua sendo acompanhado.</p><button data-action="pause">CONTINUAR</button>`;if(s==='game_over')return `<strong>GAME OVER</strong><div class="ignite-play-panel__scores"><span>SCORE <b>${formatScore(currentScore)}</b></span><span>RECORDE <b>${formatScore(bestScore)}</b></span></div><button data-action="a">JOGAR DE NOVO</button><button class="is-secondary" data-action="back">OUTROS JOGOS</button>`;return'';}
function applyState(s){if(!activeMeta||!overlay)return;if(s==='game_over'){bestScore=setHighScoreIfBetter(activeMeta.id,currentScore);q('best').textContent=formatScore(bestScore);}const p=q('panel');p.innerHTML=panelMarkup(s);p.classList.toggle('is-visible',s!=='playing');q('state-label').textContent=stateLabel(s);overlay.querySelector('.ignite-play-live').classList.toggle('is-active',s==='playing');overlay.dataset.state=s;}
function prepareGameView(meta){activeGame?.destroy();activeGame=null;activeMeta=meta;currentScore=0;bestScore=getHighScore(meta.id);q('library-view').hidden=true;q('game-view').hidden=false;overlay.dataset.view='game';overlay.dataset.controls=meta.controlMode||'all';overlay.querySelector('[data-action="back"]').hidden=false;q('game-icon').textContent=meta.icon;q('game-name').textContent=meta.name;q('control-hint').textContent=meta.controls;q('score').textContent='000';q('best').textContent=formatScore(bestScore);}
async function launchGame(id){const meta=getGame(id);if(!meta||!overlay)return;const seq=++launchSeq;prepareGameView(meta);applyState('loading');try{const factory=await loadGame(id);if(seq!==launchSeq||!overlay||activeMeta?.id!==id)return;activeGame=factory({canvas:q('canvas'),onScoreChange:v=>{currentScore=v;if(q('score'))q('score').textContent=formatScore(v);},onStateChange:applyState});applyState(activeGame.getState());}catch(error){console.error('[Ignite Play] Falha ao carregar jogo:',id,error);if(seq!==launchSeq||!overlay)return;const p=q('panel');p.innerHTML=`<strong>NÃO FOI POSSÍVEL CARREGAR</strong><p>Verifique sua conexão e tente novamente.</p><button data-game-id="${id}">TENTAR DE NOVO</button><button class="is-secondary" data-action="back">VOLTAR</button>`;p.classList.add('is-visible');q('state-label').textContent='OFFLINE';overlay.dataset.state='error';}}
function handleStart(){if(!activeGame)return;const s=activeGame.getState();s==='playing'?activeGame.pause():s==='paused'?activeGame.resume():activeGame.start();}
function handleA(){if(!activeGame)return;const s=activeGame.getState();if(s==='paused'){activeGame.resume();return;}if(s!=='playing'){activeGame.start();return;}activeGame.action?.('primary');}
function wire(){overlay.addEventListener('click',e=>{const g=e.target.closest('[data-game-id]');if(g){launchGame(g.dataset.gameId);return;}const a=e.target.closest('[data-action]');if(!a)return;if(a.dataset.action==='close')IgnitePlay.hide();else if(a.dataset.action==='back')renderLibrary();else if(a.dataset.action==='pause')handleStart();else if(a.dataset.action==='a')handleA();});overlay.querySelectorAll('[data-dir]').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture?.(e.pointerId);activeGame?.setDirection(btn.dataset.dir);});const release=()=>{if(activeMeta?.continuous)activeGame?.setDirection('stop');};btn.addEventListener('pointerup',release);btn.addEventListener('pointercancel',release);btn.addEventListener('lostpointercapture',release);});keydownHandler=e=>{const d=KEY_DIRECTIONS[e.key];if(d&&activeGame){e.preventDefault();activeGame.setDirection(d);return;}if((e.key==='Enter'||e.key===' ')&&activeGame){e.preventDefault();handleA();return;}if(e.key==='Escape'){e.preventDefault();activeMeta?renderLibrary():IgnitePlay.hide();}};document.addEventListener('keydown',keydownHandler);const stopKeyboard=e=>{if(KEY_DIRECTIONS[e.key]&&activeMeta?.continuous)activeGame?.setDirection('stop');};document.addEventListener('keyup',stopKeyboard);keydownHandler._keyup=stopKeyboard;const w=q('canvas-wrap');w.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId});w.addEventListener('pointerup',e=>{if(!pointerStart||e.pointerId!==pointerStart.id){pointerStart=null;return;}const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<SWIPE_THRESHOLD){activeGame?.action?.('tap');return;}activeGame?.setDirection(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));});w.addEventListener('pointercancel',()=>pointerStart=null);}
function unwire(){if(keydownHandler){document.removeEventListener('keydown',keydownHandler);if(keydownHandler._keyup)document.removeEventListener('keyup',keydownHandler._keyup);}keydownHandler=null;pointerStart=null;}

export const IgnitePlay={show(o={}){const{orderId=null,orderNumber='',onClose,gameId=null}=o;if(overlay){overlay.dataset.orderId=orderId??'';currentOrderNumber=orderNumber||currentOrderNumber;q('order-label').textContent=currentOrderNumber?`Pedido #${currentOrderNumber}`:'';if(gameId&&getGame(gameId))launchGame(gameId);return;}ensureStyles();previousFocus=document.activeElement;onCloseCallback=typeof onClose==='function'?onClose:null;currentOrderNumber=orderNumber?String(orderNumber):'';const w=document.createElement('div');w.innerHTML=MARKUP;overlay=w.firstElementChild;overlay.dataset.orderId=orderId??'';document.documentElement.classList.add(LOCK_CLASS);document.body.classList.add(LOCK_CLASS);document.body.appendChild(overlay);q('order-label').textContent=currentOrderNumber?`Pedido #${currentOrderNumber}`:'';wire();gameId&&getGame(gameId)?launchGame(gameId):renderLibrary();},hide(){if(!overlay)return;launchSeq++;const cb=onCloseCallback;activeGame?.destroy();unwire();overlay.remove();overlay=null;activeGame=activeMeta=null;document.documentElement.classList.remove(LOCK_CLASS);document.body.classList.remove(LOCK_CLASS);if(previousFocus instanceof HTMLElement)previousFocus.focus();previousFocus=null;onCloseCallback=null;cb?.();},destroy(){this.hide();},isOpen(){return!!overlay;},getScore(){return currentScore;},getActiveGame(){return activeMeta?.id||null;},listGames};
export default IgnitePlay;
