import { getSupabase } from './supabase-client.js';

const STORAGE_KEY = 'ignite-profile-v1';
const PLAY_TOKEN_KEY = 'ignite-play-player-token-v1';
const cleanPhone = value => String(value || '').replace(/\D/g, '').slice(0, 13);

export function getLocalProfile() { try { return { name:'',phone:'',email:'',address:'',birth_date:'',marketing_opt_in:false,...(JSON.parse(localStorage.getItem(STORAGE_KEY))||{}) }; } catch { return { name:'',phone:'',email:'',address:'',birth_date:'',marketing_opt_in:false }; } }
export function saveLocalProfile(profile) { const next={...getLocalProfile(),...profile}; localStorage.setItem(STORAGE_KEY,JSON.stringify(next)); return next; }
export async function getSession(){const s=await getSupabase();const{data,error}=await s.auth.getSession();if(error)throw error;return data?.session||null;}
export async function getAccountProfile(){const s=await getSupabase();const{data:sd}=await s.auth.getSession();const session=sd?.session;if(!session?.user?.id)return{session:null,profile:null};const{data,error}=await s.rpc('get_my_customer_profile');if(error)throw error;return{session,profile:data||null};}
export async function getProfileHub(){const s=await getSupabase();const{data,error}=await s.rpc('get_my_profile_hub');if(error)throw error;return data||{authenticated:false,orders:[],stats:{}};}
export async function syncCustomerAccount(seed={}){const s=await getSupabase();const{data:sd,error:se}=await s.auth.getSession();if(se)throw se;const session=sd?.session;if(!session?.user?.id)return null;let{data:current,error:ce}=await s.rpc('get_my_customer_profile');if(ce)throw ce;const local=saveLocalProfile({...getLocalProfile(),...seed,email:seed.email||session.user.email||getLocalProfile().email||''});if(!current){if(!local.name||!cleanPhone(local.phone))return null;const{data,error}=await s.rpc('link_my_customer_profile',{p_name:local.name,p_phone:cleanPhone(local.phone),p_email:session.user.email||local.email||null});if(error)throw error;current=data;}const playToken=localStorage.getItem(PLAY_TOKEN_KEY);if(playToken?.length>=32){const{error}=await s.rpc('link_ignite_play_player',{p_player_token:playToken});if(error)console.warn('[Perfil] Ignite Play:',error.message);}if(current)saveLocalProfile({name:current.name||local.name,phone:current.phone||local.phone,email:current.email||session.user.email||local.email,address:current.address||local.address,birth_date:current.birth_date||local.birth_date||'',marketing_opt_in:Boolean(current.marketing_opt_in)});return current;}
export async function signUpCustomer({name,phone,email,password}){const s=await getSupabase(),e=String(email||'').trim().toLowerCase(),p=cleanPhone(phone);saveLocalProfile({name:String(name||'').trim(),phone:p,email:e});const{data,error}=await s.auth.signUp({email:e,password,options:{data:{full_name:String(name||'').trim(),phone:p}}});if(error)throw error;if(data?.session)await syncCustomerAccount({name,phone:p,email:e});return data;}
async function signInByPhone(s,phone,password){const p=cleanPhone(phone);if(p.length<10)throw new Error('Informe um telefone válido com DDD.');const{data,error}=await s.functions.invoke('customer-phone-login',{body:{phone:p,password}});if(error)throw new Error('Telefone ou senha inválidos.');if(!data?.access_token||!data?.refresh_token)throw new Error(data?.error||'Telefone ou senha inválidos.');const{data:sd,error:se}=await s.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(se||!sd?.session)throw se||new Error('Não foi possível iniciar sua sessão.');saveLocalProfile({phone:p,email:sd.user?.email||getLocalProfile().email||''});return sd;}
export async function signInCustomer({login_type='email',email,phone,identifier,password}){const s=await getSupabase();let data;if(login_type==='phone')data=await signInByPhone(s,phone||identifier,password);else{const e=String(email||identifier||'').trim().toLowerCase(),r=await s.auth.signInWithPassword({email:e,password});if(r.error)throw r.error;data=r.data;saveLocalProfile({email:data?.user?.email||e});}await syncCustomerAccount({email:data?.user?.email||getLocalProfile().email||'',phone:login_type==='phone'?cleanPhone(phone||identifier):getLocalProfile().phone||''});return data;}
export async function signOutCustomer(){const s=await getSupabase();const{error}=await s.auth.signOut();if(error)throw error;}
export async function requestPasswordReset(email){const s=await getSupabase();const{error}=await s.auth.resetPasswordForEmail(String(email||'').trim().toLowerCase(),{redirectTo:`${location.origin}${location.pathname}#profile`});if(error)throw error;}
export async function updatePassword(password){const s=await getSupabase();const{data,error}=await s.auth.updateUser({password:String(password||'')});if(error)throw error;return data?.user||null;}
export async function saveProfile(profile){const local=saveLocalProfile({...profile,phone:cleanPhone(profile.phone),marketing_opt_in:Boolean(profile.marketing_opt_in)}),s=await getSupabase();const{data:sd}=await s.auth.getSession(),session=sd?.session;if(!session?.user?.id)return local;let{data:account}=await s.rpc('get_my_customer_profile');if(!account)account=await syncCustomerAccount(local);if(!account?.id)return local;const updates={name:local.name,phone:cleanPhone(local.phone),address:local.address||null,birth_date:local.birth_date||null,marketing_opt_in:Boolean(local.marketing_opt_in),updated_at:new Date().toISOString()};const{data,error}=await s.from('customers').update(updates).eq('auth_user_id',session.user.id).select().single();if(error)throw error;saveLocalProfile({...local,...data,email:session.user.email||local.email});return data;}
export async function saveCustomerAddress(address){const s=await getSupabase();const{data:p,error:pe}=await s.rpc('get_my_customer_profile');if(pe)throw pe;if(!p?.id)throw new Error('Perfil do cliente não encontrado.');const payload={customer_id:p.id,label:String(address.label||'Casa').trim(),street:String(address.street||'').trim(),number:String(address.number||'').trim(),complement:String(address.complement||'').trim()||null,neighborhood:String(address.neighborhood||'').trim()||null,city:String(address.city||'').trim(),state:String(address.state||'').trim().toUpperCase().slice(0,2),zip:String(address.zip||'').replace(/\D/g,''),reference:String(address.reference||'').trim()||null,is_default:Boolean(address.is_default),updated_at:new Date().toISOString()};if(payload.is_default)await s.from('customer_addresses').update({is_default:false}).eq('customer_id',p.id);const q=address.id?s.from('customer_addresses').update(payload).eq('id',address.id).eq('customer_id',p.id):s.from('customer_addresses').insert(payload);const{data,error}=await q.select().single();if(error)throw error;return data;}
export async function deleteCustomerAddress(id){const s=await getSupabase();const{data:p,error:pe}=await s.rpc('get_my_customer_profile');if(pe)throw pe;if(!p?.id)throw new Error('Perfil do cliente não encontrado.');const{error}=await s.from('customer_addresses').delete().eq('id',id).eq('customer_id',p.id);if(error)throw error;}
export function onAuthStateChange(callback){let subscription;getSupabase().then(s=>{subscription=s.auth.onAuthStateChange((event,session)=>setTimeout(()=>callback?.(event,session),0))?.data?.subscription;}).catch(console.warn);return()=>subscription?.unsubscribe?.();}
