import { getOrders, subscribeToOrders, subscribeToOrder } from '../services/order-service.js';
import { escapeHTML, money, shortDate } from '../utils/format.js';
const STATUS = { pending:['Pedido recebido',1], confirmed:['Pedido confirmado',2], preparing:['Em preparação',3], ready:['Pronto',4], out_for_delivery:['Saiu para entrega',5], delivered:['Entregue',6], cancelled:['Cancelado',0] };
const ORDER_TYPE = { delivery:['Delivery','Entrega no endereço'], pickup:['Retirada','Retirada no balcão'], retirada:['Retirada','Retirada no balcão'], local:['No local','Atendimento na mesa'] };
const PROGRESS_LABELS = { delivery:['Recebido','Confirmado','Em preparação','Pronto','Saiu para entrega','Entregue'] };
export const WAITING_STATUSES = new Set(['pending','confirmed','preparing']);
export const isWaitingStatus = status => WAITING_STATUSES.has(status);
export function initOrders({ onPlayRequested } = {}) {
  const root=document.querySelector('#order-list'); let unsubscribe=()=>{},lastOrders=[],destroyed=false,requestVersion=0,revision=0; const watchers=new Map(),realtimeChannels=new Map(); const orderKey=o=>String(o.id??'');
  const notifyWatchers=orders=>orders.forEach(order=>watchers.get(orderKey(order))?.forEach(cb=>{try{cb(order.status,order)}catch(e){console.warn(e)}}));
  const render=orders=>{ lastOrders=orders; syncChannels(orders); if(!orders.length){root.innerHTML='<div class="empty-state"><span>🧾</span><h3>Nenhum pedido ainda</h3><p>Quando você pedir, o acompanhamento aparecerá aqui.</p></div>';notifyWatchers(orders);return} root.innerHTML=orders.map(order=>{const [label,progress]=STATUS[order.status]||[order.status,1];const items=(order.order_items||[]).map(i=>`${i.quantity}× ${escapeHTML(i.product_name||i.name||'Produto')}`).join(' · ');const raw=order.order_number||order.numero_pedido||order.id;const number=order.order_number||(typeof raw==='number'?`IG${String(raw).padStart(6,'0')}`:raw);const typeKey=order.order_type||order.service_type||order.tipo||'delivery';const [typeLabel,typeDetail]=ORDER_TYPE[typeKey]||[typeKey,'Pedido Ignite'];const destination=typeKey==='local'&&order.table_number?`${typeDetail} ${order.table_number}`:typeDetail;const steps=PROGRESS_LABELS[typeKey]||PROGRESS_LABELS.delivery;const progressHTML=steps.map((s,i)=>`<span class="${progress>=i+1?'is-done':''}">${escapeHTML(s)}</span>`).join('');const card=`<article class="order-card"><div class="order-card__top"><div><div class="order-card__number">Pedido ${escapeHTML(number)}</div><div class="order-card__date">${shortDate(order.created_at||order.criado_em)}</div></div><span class="status-pill" data-status="${escapeHTML(order.status)}">${escapeHTML(label)}</span></div><div class="order-card__service"><strong>${escapeHTML(typeLabel)}</strong><span>${escapeHTML(destination)}</span></div><p class="order-card__items">${items||'Itens do pedido'}</p><div class="order-card__footer"><span>Total</span><strong>${money(order.total)}</strong></div>${order.status!=='cancelled'?`<div class="order-progress">${progressHTML}</div>`:''}</article>`;const play=order.id!=null&&!order.offline&&isWaitingStatus(order.status)?`<button type="button" class="order-play-cta" data-order-key="${escapeHTML(orderKey(order))}"><span class="order-play-cta__icon"><i class="fi fi-rr-game-console-crank-handheld"></i></span><span class="order-play-cta__copy"><strong>Jogue enquanto espera</strong><small>Divirta-se enquanto preparamos seu pedido</small></span><span class="order-play-cta__arrow">&rsaquo;</span></button>`:'';return card+play}).join('');notifyWatchers(orders)};
  const syncChannels=orders=>{const ids=new Set(orders.filter(o=>o.id!=null&&!o.offline).map(orderKey));realtimeChannels.forEach((e,id)=>{if(!ids.has(id)){e.cancelled=true;e.cleanup?.();realtimeChannels.delete(id)}});orders.forEach(order=>{if(order.offline||order.id==null)return;const id=orderKey(order);if(realtimeChannels.has(id))return;const entry={cancelled:false,cleanup:null};realtimeChannels.set(id,entry);subscribeToOrder(order.id,{onChange:p=>{if(destroyed||entry.cancelled)return;revision++;if(p.eventType==='DELETE')render(lastOrders.filter(o=>orderKey(o)!==id));else render(lastOrders.map(o=>orderKey(o)===id?{...o,...p.new}:o))}}).then(c=>{if(destroyed||entry.cancelled)c();else entry.cleanup=c}).catch(console.warn)})};
  const watchOrder=(orderId,callback)=>{if(orderId==null)throw new Error('orders.id obrigatório.');const id=String(orderId);if(!watchers.has(id))watchers.set(id,new Set());watchers.get(id).add(callback);const order=lastOrders.find(o=>orderKey(o)===id);if(order)callback(order.status,order);return()=>{watchers.get(id)?.delete(callback);if(!watchers.get(id)?.size)watchers.delete(id)}};
  const load=async()=>{const request=++requestVersion,version=revision;try{const orders=await getOrders();if(destroyed||request!==requestVersion||version!==revision)return;render(orders)}catch(error){console.error('[Pedidos] Falha ao carregar pedidos do cliente.',error);if(!destroyed&&request===requestVersion&&!lastOrders.length)root.innerHTML='<div class="empty-state"><h3>Não foi possível atualizar seus pedidos</h3><p>Verifique sua conexão e tente novamente.</p></div>'}};
  const onClick=e=>{const cta=e.target.closest('.order-play-cta');if(!cta)return;const order=lastOrders.find(o=>orderKey(o)===cta.dataset.orderKey);if(order)onPlayRequested?.(order)};root.addEventListener('click',onClick);const refresh=document.querySelector('#refresh-orders');refresh?.addEventListener('click',load);subscribeToOrders(load).then(c=>{if(destroyed)c();else unsubscribe=c}).catch(console.warn);void load();return{load,watchOrder,destroy:()=>{destroyed=true;requestVersion++;unsubscribe();root.removeEventListener('click',onClick);refresh?.removeEventListener('click',load);watchers.clear();realtimeChannels.forEach(e=>{e.cancelled=true;e.cleanup?.()});realtimeChannels.clear()}};
}
