import { getAccountProfile, saveProfile } from '../services/profile-service.js';
import { cancelAccountDeletion, getCurrentSessionInfo, getPrivacySnapshot, removeMyAvatar, requestAccountDeletion, signOutOtherSessions, uploadMyAvatar } from '../services/profile-privacy-service.js';

const fmtDate = value => { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(d); };
const initials = name => String(name || 'Cliente Ignite').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase();

function ensureStyles(){if(document.querySelector('[data-profile-privacy-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=new URL('../../styles/profile-privacy.css?v=20260913-1',import.meta.url).href;l.setAttribute('data-profile-privacy-style','true');document.head.appendChild(l);}
function toast(title,icon='success'){window.Swal?.fire({toast:true,position:'top-end',icon,title,timer:1600,showConfirmButton:false});}

function completion(profile){const checks=[profile?.name,profile?.phone,profile?.birth_date,profile?.avatar_url,Array.isArray(profile?.addresses)&&profile.addresses.length>0];const score=Math.round(checks.filter(Boolean).length/checks.length*100);return {score,missing:[!profile?.avatar_url&&'foto',!profile?.birth_date&&'nascimento',!(profile?.addresses?.length)&&'endereço'].filter(Boolean)};}

function downloadJson(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ignite-meus-dados-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function initProfilePrivacy(){ensureStyles();let lastProfile=null;let decorating=false;
const decorate=async()=>{if(decorating)return;const hub=document.querySelector('#view-profile .profile-hub');if(!hub||hub.querySelector('[data-profile-privacy]'))return;decorating=true;try{const {session,profile}=await getAccountProfile();if(!session||!profile)return;lastProfile=profile;const c=completion(profile);const hero=hub.querySelector('.profile-hub__hero');if(hero){const avatar=hero.querySelector('.profile-hub__avatar');if(avatar){avatar.innerHTML=profile.avatar_url?`<img src="${String(profile.avatar_url).replace(/"/g,'&quot;')}" alt="Foto de perfil">`:initials(profile.name);avatar.classList.toggle('has-image',Boolean(profile.avatar_url));avatar.insertAdjacentHTML('beforeend','<button type="button" class="profile-avatar-edit" data-profile-avatar aria-label="Alterar foto"><i class="fi fi-rr-camera"></i></button>');}}
const section=document.createElement('section');section.className='profile-section profile-privacy';section.setAttribute('data-profile-privacy','true');section.innerHTML=`<div class="profile-section__head"><div><strong>Conta, privacidade e segurança</strong><small>Controle seus dados e acesso à conta</small></div></div><div class="profile-completion"><div class="profile-completion__row"><span>Perfil completo</span><strong>${c.score}%</strong></div><div class="profile-completion__bar"><span style="width:${c.score}%"></span></div><small>${c.score===100?'Seu perfil está completo.':`Falta: ${c.missing.join(', ') || 'alguns dados opcionais'}.`}</small></div><div class="profile-security-grid"><button type="button" data-privacy-export><i class="fi fi-rr-download"></i><span><strong>Baixar meus dados</strong><small>Exportar uma cópia em JSON</small></span></button><button type="button" data-security-sessions><i class="fi fi-rr-devices"></i><span><strong>Encerrar outras sessões</strong><small>Desconectar outros aparelhos</small></span></button><button type="button" data-security-info><i class="fi fi-rr-shield-check"></i><span><strong>Segurança da conta</strong><small>Ver último acesso e sessão</small></span></button><button type="button" class="is-danger" data-account-delete><i class="fi fi-rr-user-delete"></i><span><strong>Solicitar exclusão da conta</strong><small>Registrar pedido de exclusão</small></span></button></div></section>`;hub.appendChild(section);}catch(error){console.warn('[Perfil/Privacidade]',error);}finally{decorating=false;}};

const observer=new MutationObserver(()=>void decorate());observer.observe(document.body,{childList:true,subtree:true});void decorate();

document.addEventListener('click',async event=>{const avatarButton=event.target.closest('[data-profile-avatar]');if(avatarButton){const result=await Swal.fire({title:'Foto de perfil',html:'<input id="profile-avatar-file" type="file" accept="image/jpeg,image/png,image/webp" class="swal2-file"><p style="font-size:.78rem;color:#748077">JPG, PNG ou WebP · até 5 MB</p>',showCancelButton:true,showDenyButton:Boolean(lastProfile?.avatar_url),confirmButtonText:'Salvar foto',denyButtonText:'Remover foto',cancelButtonText:'Cancelar',preConfirm:()=>{const file=document.querySelector('#profile-avatar-file')?.files?.[0];if(!file){Swal.showValidationMessage('Selecione uma imagem.');return false;}return file;}});try{if(result.isDenied){await removeMyAvatar();toast('Foto removida');document.querySelector('[data-profile-privacy]')?.remove();await decorate();location.hash='#profile';}else if(result.isConfirmed){await uploadMyAvatar(result.value);toast('Foto atualizada');document.querySelector('[data-profile-privacy]')?.remove();await decorate();location.hash='#profile';}}catch(error){Swal.fire({icon:'error',title:'Não foi possível atualizar a foto',text:error.message});}return;}

if(event.target.closest('[data-privacy-export]')){try{const data=await getPrivacySnapshot();downloadJson(data);toast('Cópia dos seus dados preparada');}catch(error){Swal.fire({icon:'error',title:'Não foi possível exportar',text:error.message});}return;}
if(event.target.closest('[data-security-sessions]')){const r=await Swal.fire({icon:'question',title:'Encerrar outras sessões?',text:'Este aparelho continuará conectado. Os outros precisarão entrar novamente.',showCancelButton:true,confirmButtonText:'Encerrar outras sessões',cancelButtonText:'Cancelar'});if(r.isConfirmed){try{await signOutOtherSessions();toast('Outras sessões encerradas');}catch(error){Swal.fire({icon:'error',title:'Falha ao encerrar sessões',text:error.message});}}return;}
if(event.target.closest('[data-security-info]')){try{const info=await getCurrentSessionInfo();await Swal.fire({title:'Segurança da conta',html:`<div class="profile-security-info"><div><span>E-mail</span><strong>${info?.email||'—'}</strong></div><div><span>Conta criada</span><strong>${fmtDate(info?.created_at)}</strong></div><div><span>Último acesso</span><strong>${fmtDate(info?.last_sign_in_at)}</strong></div><div><span>Sessão expira</span><strong>${info?.expires_at?fmtDate(info.expires_at*1000):'—'}</strong></div></div>`,confirmButtonText:'Fechar'});}catch(error){toast('Não foi possível consultar a sessão','error');}return;}
if(event.target.closest('[data-account-delete]')){try{const snapshot=await getPrivacySnapshot();if(snapshot?.deletion_request){const r=await Swal.fire({icon:'warning',title:'Solicitação já registrada',text:'Sua solicitação de exclusão está pendente. Você pode cancelá-la enquanto ainda não estiver em processamento.',showCancelButton:true,confirmButtonText:'Manter solicitação',cancelButtonText:'Cancelar solicitação'});if(r.dismiss===Swal.DismissReason.cancel){await cancelAccountDeletion();toast('Solicitação cancelada');}return;}const r=await Swal.fire({icon:'warning',title:'Solicitar exclusão da conta?',text:'Isso registra formalmente o pedido. A conta não é apagada imediatamente.',input:'textarea',inputPlaceholder:'Motivo (opcional)',showCancelButton:true,confirmButtonText:'Solicitar exclusão',cancelButtonText:'Voltar'});if(r.isConfirmed){await requestAccountDeletion(r.value||'');await Swal.fire({icon:'success',title:'Solicitação registrada',text:'O pedido de exclusão foi registrado com segurança.'});}}catch(error){Swal.fire({icon:'error',title:'Não foi possível registrar',text:error.message});}return;}
});

return()=>observer.disconnect();}
